### Recuperar peliculas
GET http://localhost:1234/movies

### Recuperar por id
GET http://localhost:1234/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf

### Recuperar por genero
GET http://localhost:1234/movies?genre=sci-fi

### Crear una pelicula
POST http://localhost:1234/movies
Content-Type: application/json

{
  "title": "Matrix",
  "year": 1999,
  "director": "Lana Wachowski",
  "duration": 135,
  "poster": "https://i.pinimg.com/originals/42/42/65/4242658e6f1b0d6322a4a93e0383108b.png",
  "genre": ["Crime", "Drama"],
  "rate": 5
}

### Actualizar una pelicula
PATCH http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
  "year": 1994
}
